# Workflow for building and deploying an Astro site to GitHub Pages
name: Build and Deploy Astro Site to GitHub Pages

on:
  # Trigger on pushes to the main branch
  push:
    branches: ["main"]
  # Allow manual trigger
  workflow_dispatch:

# Set permissions for GITHUB_TOKEN to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.set-artifact-path.outputs.artifact-path }}
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

        # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Astro project
      - name: Build Astro project
        run: npm run build

      # Step 5: Prepare artifact path output
      - name: Set artifact path
        id: set-artifact-path
        run: echo "artifact-path=dist" >> $GITHUB_ENV

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Download build artifact
      - name: Download build artifact
        uses: actions/download-pages-artifact@v3
        with:
          path: ${{ env.artifact-path }}

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
